A3/HousePartyFinder/config/routes.rb
Rails.application.routes.draw do

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#rejected'
  get '/500', :to => 'errors#server_error'

  root 'static_pages#home'
  get 'register_login' => 'static_pages#register_login'
  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'site_map' => 'static_pages#site_map'
  get 'about_us' => 'static_pages#about_us'

 devise_for :users do
    resource :registration, :only => [:new, :create, :edit, :update],
      as: :user_registration do
        get :cancel
      end
  end
  
  get '/parties/featured' => 'parties#featured'
  get '/parties/streaming' => 'parties#streaming'
  get '/parties/my-parties' => 'parties#mine'
  resources :parties do
    post 'attend' => 'parties#attend', :as => :attend
    post 'unattend' => 'parties#unattend', :as => :unattend
    post 'feature' => 'parties#feature', :as => :feature
    post 'unfeature' => 'parties#unfeature', :as => :unfeature
    post 'attach' => 'parties#attach', :as => :attach
    get 'stream_in' => 'parties#stream_in', :as => :stream_in
    get 'stream_out' => 'parties#stream_out', :as => :stream_out
  end
  post '/parties/:id/rate' => 'parties#rate'
  patch '/parties/:id/complete' => 'parties#complete'
  
  resources :users do
    get 'profile' => 'users#profile', :as => :profile
    get 'activity' => 'users#activity', :as => :activity
    get 'subscribers' => 'users#subscribers', :as => :subscribers
    get 'portfolio' => 'users#portfolio', :as => :portfolio
    post 'subscribe' => 'users#subscribe', :as => :subscribe
    post 'unsubscribe' => 'users#unsubscribe', :as => :unsubscribe
  end
  

end

A3/HousePartyFinder/app/models/party.rb
class Party < ActiveRecord::Base
	belongs_to :host, :class_name => 'User'
	has_many :ratings
	has_many :raters, :through => :ratings, :source => :user
	has_many :attendances
	has_many :attendees, :class_name => 'User', :through => :attendances, :source => :user
  has_many :album_attachments

  has_attached_file :avatar, :url => '/system/uploads/party_avatar_:style_:id.:extension', :path => ":rails_root/public:url", :styles => { :medium => "240x240>", :thumbnail => "100x100>" }, :default_url => "/images/house.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :name, :presence => true
  validates :capacity, :presence => true, :numericality => { :only_integer => true }
  validates :address, :city, :province, :presence => true
  validates :latitude, :longitude, :numericality => true
  validates :start_date, :presence => true
  validate :cannot_be_in_the_past
  validates :featured_until, :absence => true, :on => :create
  validates :streaming, :food_provided, :alcohol, :parking, :adult_only, :inclusion => { :in => [true, false] }

    def rating_score
  	  Party.where({ id: self.id }).joins(:ratings).average(:score) || 0
    end

    def rating_count
  	  Party.where({ id: self.id }).joins(:ratings).count
    end

    def similar
      keywords = self.name.split.map { |x| ActiveRecord::Base.connection.quote(x).slice(1, -1) }
      p = Party.arel_table
      matcher = p[:name].matches("%#{keywords[0]}%")
      keywords.each do |kw|
        if (kw != keywords[0])
          matcher = matcher.or(p[:name].matches("%#{kw}%"))
        end
      end
      return Party.where(matcher).where.not(:id => self.id)
    end

  private

    def cannot_be_in_the_past
      errors.add(:start_date, "cannot be in the past.") if !start_date.blank? && start_date < Date.today
    end
end

A3/HousePartyFinder/app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy, :rate, :complete]
  before_action :set_fragment_party, only: [:feature, :unfeature, :attend, :unattend, :attach, :stream_in, :stream_out]
  before_filter :logged_in_only, except: [:show, :index, :featured, :streaming]
  before_filter :owner_only, only: [:edit, :update, :destroy, :complete, :stream_in]
  before_filter :admin_only, only: [:feature, :unfeature]
  layout 'streaming_fragment', only: [:stream_in, :stream_out]

  # GET /parties
  def index
    @empty_query = params[:q][:name_cont].blank?
    unless @empty_query
      @q = Party.ransack(params[:q])
      @parties = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /parties/featured
  def featured
    @parties = Party.where('featured_until > ?', Date.today).paginate(:page => params[:page], :per_page => 12)
  end

  # GET /parties/streaming
  def streaming
    @parties = Party.where(:streaming => true).paginate(:page => params[:page], :per_page => 12)
  end

  # GET /parties/my-parties
  def mine
    @parties = current_user.hosted_parties.where(:ended => [false, nil]).paginate(:page => params[:page], :per_page => 12)
    @all_parties = Party.where(:ended => [false, nil]).paginate(:page => params[:page], :per_page => 12)
  end

  # GET /parties/1
  def show
    @similar_parties = @party.similar.where('start_date > ?', Date.today).limit(12)
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  def create
    @party = Party.new(party_params)
    @party.host = current_user

    if @party.save
      redirect_to @party, notice: 'Party was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /parties/1
  def update
    if @party.update(party_params)
      redirect_to @party, notice: 'Party was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /parties/1
  def destroy
    @party.destroy
    redirect_to parties_url, notice: 'Party was successfully destroyed.'
  end

  # POST /parties/1/rate
  def rate
    @rating = Rating.new(rating_params)
    @rating.user = current_user
    @rating.party = @party
    
    if !(@party.raters.include?(current_user))
    	if @rating.save
      	  respond_to do |format|
            format.json { render json: { ok: true, score: @party.rating_score, count: @party.rating_count } }
          end
	else	
      	  respond_to do |format|
            format.json { render json: { ok: false } }
      	  end
    	end
    else
      respond_to do |format|
        format.json { render json: { ok: false } }
      end
    end
  end

  # POST /parties/1/complete
  def complete
    @party.ended = true
    if (current_user == @party.host) && @party.save
      respond_to do |format|
        format.json { render json: { ok: true, ended: @party.ended } }
      end
    else
      respond_to do |format|
        format.json { render json: { ok: false } }
      end
    end
  end

  # POST /parties/1/attend
  def attend
    unless @party.host == current_user || @party.attendees.include?(current_user)
      @party.attendees << current_user
      @party.save
    end
    redirect_to :back
  end

  # POST /parties/1/unattend
  def unattend
    if @party.attendees.include?(current_user)
      @party.attendees.delete(current_user)
      @party.save
    end
    redirect_to :back
  end

  # POST /parties/1/attach
  def attach
    if @party.host == current_user
      @album_attachment = AlbumAttachment.new(album_attachment_params)
      @album_attachment.party = @party

      if @album_attachment.save
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end


  # GET /parties/1/stream_in
  def stream_in
  end

  # GET /parties/1/stream_out
  def stream_out
  end

  # POST /parties/1/feature
  def feature
     @party.featured_until = 15.day.from_now
     if @party.save
	redirect_to :back
     else
	redirect_to root_url
     end
  end

  # POST /parties/1/unfeature
  def unfeature
     @party.featured_until = nil
     if @party.save
	redirect_to :back
     else
	redirect_to root_url
     end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end
    def set_fragment_party
      @party = Party.find(params[:party_id])
    end

    # Only allow a trusted parameter "white list" through.
    def party_params
      params.require(:party).permit(:name, :capacity, :address, :city, :province, :latitude, :longitude, :description, :posted_date, :start_date, :end_date, :ended, :featured_until, :streaming, :private, :food_provided, :alcohol, :parking, :adult_only, :avatar)
    end

    def rating_params
      params.require(:rating).permit(:score, :comment)
    end

    def album_attachment_params
      params.require(:album_attachment).permit(:picture)
    end

    # Must be logged in
    def logged_in_only
      unless signed_in?
        redirect_to '/register_login', notice: "You must be logged in to use this functionality."
      end
    end

    # Restrict to owner only
    def owner_only
      unless @party.host == current_user
        redirect_to root_url, notice: "You must be logged in as that user to make this change."
      end
    end
    
    def admin_only
      unless current_user.admin
	redirect_to root_url, notice: "You must be an admin to make this change."
      end
    end
    
end

A3/HousePartyFinder/app/helpers/parties_helper.rb
module PartiesHelper
end

A3/HousePartyFinder/app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

A3/HousePartyFinder/app/views/parties/featured.html.erb
<% content_for :head do %>
	<link rel="stylesheet" href="/styles/homepage.css" >
<% end %>

<% content_for :title, "Featured Parties" %>

<div class="featured-heading">
	<h2>Featured Parties</h2>
</div>

<% if @parties.empty? %>
	<p class="featured-no-result">No parties are currently being featured.</p>
<% else %>
	<ul class="featured-list">
		<% @parties.each do |party| %>
			<li><%= link_to party_url(party) do %><div class="featured-div">
				<%= image_tag party.avatar.url(:thumbnail) %>
				<h4><%= party.name %></h4>
				<p><%= party.city %>, <%= party.province %></p>
				<p>Attendance: <%= party.attendees.count %>/<%= party.capacity %></p>
			</div><% end %></li>
		<% end %>
	</ul>
	<p>
		<%= will_paginate %>
	</p>
<% end %>

A3/HousePartyFinder/app/views/parties/index.html.erb
<% content_for :head do %>
  <link rel="stylesheet" type="text/css" href="/styles/LogIn.css" >
  <link rel="stylesheet" type="text/css" href="/styles/SearchResult.css" >
<% end %>

<% content_for :title, "Searching for #{params[:q]}" %>

<% if @empty_query %>
  <p>Please enter a search query.</p>
<% elsif @parties == [] %>
  <p>No parties are found for "<%= params[:q][:name_cont] %>".</p>
<% else %>
  <% @parties.each do |party| %>
    <div class="search-table-first">
      <a href="<%= party_path(party) %>">
        <div class="search-row">
          <%= image_tag party.avatar.url(:thumbnail), :width => 100, :height => 100, :class => "preview-image" %>
          <div class="party-info">
            <div class="party-info-text">
              <div class="party-info-text-left">
                <h4 class="party-title"> Party Title: <%= party.name %> </h4>
                <div class="date">Date: <span class="date-answer"><%= party.start_date.strftime("%F %r") %></span></div>
              </div>
              <div class="party-info-text-right">
                <div class="location">Location: <span class = "location-answer"><%= party.address + ', ' + party.city + ', ' + party.province %></span></div>
                <div class="attending">Attendance: <span class = "attending-answer"><%= party.attendees.count %>/<%= party.capacity %></span></div>
              </div>
            </div>
            <p class="party-desc">
              <%= truncate party.description, :length => 460, :separator => /\w/, :omission => "&hellip;" %>
            </p>          
          </div>
        </div>
      </a>
    </div>
  <% end %>
  
  <%= will_paginate %>
<% end %>

A3/HousePartyFinder/app/views/parties/mine.html.erb
<% content_for :head do %>
	<link rel="stylesheet" href="/styles/homepage.css" >
<% end %>

<% content_for :title, "My active parties" %>

<% if current_user.admin %>

  <div class="featured-heading">
	  <h2>All on-going parties</h2>
  </div>
  
  <% if @all_parties.empty? %>
	<p class="featured-no-result">There are no upcoming parties. <%= link_to "Start one!", new_party_path %></p>
  <% else %>
	<ul class="featured-list">
		  <% @all_parties.each do |party| %>
			  <li><%= link_to party_url(party) do %><div class="featured-div">
				  <%= image_tag party.avatar.url(:thumbnail) %>
				  <h4><%= party.name %></h4>
				  <p><%= party.city %>, <%= party.province %></p>
				  <p>Attendance: <%= party.attendees.count %>/<%= party.capacity %></p>
			  </div><% end %></li>
		  <% end %>
	</ul>
	<p>
		<%= will_paginate @all_parties %>
	</p>
  <% end %>
  
<% else %>
  <div class="featured-heading">
	  <h2>My active parties</h2>
  </div>
  
  <% if @parties.empty? %>
	<p class="featured-no-result">You have no upcoming parties. <%= link_to "Start one!", new_party_path %></p>
  <% else %>
    <ul class="featured-list">
	    <% @parties.each do |party| %>
		    <li><%= link_to party_url(party) do %><div class="featured-div">
			    <%= image_tag party.avatar.url(:thumbnail) %>
			    <h4><%= party.name %></h4>
			    <p><%= party.city %>, <%= party.province %></p>
			    <p>Attendance: <%= party.attendees.count %>/<%= party.capacity %></p>
		    </div><% end %></li>
	    <% end %>
    </ul>
    <p>
	    <%= will_paginate @parties %>
    </p>

  <% end %>
<% end %>

A3/HousePartyFinder/app/views/parties/new.html.erb
<% content_for :head do %>
	<link rel="stylesheet" href="/styles/homepage.css">
	<link rel="stylesheet" href="/styles/hostparty.css">
	<link rel="stylesheet" type="text/css" href="/styles/jquery.datepick.css"> 
	<script type="text/javascript" src="/script/jquery.plugin.js"></script> 
	<script type="text/javascript" src="/script/jquery.datepick.js"></script>
	<script>
	$(document).ready(function() {
		$('#datepick').datepick();
	});
	</script>
	<style>
		.middle-align-inline {
			display: inline-block;
			vertical-align: middle;
		}
	</style>
<% end %>

<% content_for :title, "Host a Party" %>

<div class="featured-heading">
	<h2>Host a New Party</h2>
</div>

<% if @party.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

		<ul>
			<% @party.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @party, :url => parties_path, :html => { multipart: true, class: "host" } do |f| %>
    <span>
    	<%= f.label "Party Name: ", :for => :name, :class => "pad10" %>
    	<%= f.text_field :name, :class => "box1", :placeholder => "Enter party name" %>
    	<br><br>
    </span>
	
	<!-- MAP SECTION -->
	<span style="float:left; padding-left:55%;"><div id="map-canvas">
	</div></span>
	<!-- MAP SECTION -->
	<%= f.hidden_field :latitude, id: "latitude" %>
	<%= f.hidden_field :longitude, id: "longitude" %>

    <span style="padding-bottom:5px;">
        <%= f.label "Province: ", :for => :province, :class => "pad10" %>
        <%= f.select :province, [
					["-- Select province --", "none"],
					["Alberta", "AB"],
					["British Columbia", "BC"],
					["Manitoba", "MB"],
					["New Brunswick", "NB"],
					["Newfoundland and Labrador", "NL"],
					["Nova Scotia", "NS"],
					["Ontario", "ON"],
					["Prince Edward Island", "PE"],
					["Quebec", "QC"],
					["Saskatchewan", "SK"],
					["Northwest Territories", "NT"],
					["Nunavut", "NU"],
					["Yukon", "YT"]
				], {}, id: "province", class: "fr", required: "required", onChange: "clearCity(); codeAddress()",
				style: "margin-bottom:8px; padding-bottom:1px; padding-top:1px;" %>
        <br>
    </span>
	<span>
		<%= f.label "City: ", :for => :city, :class => "pad10" %>
		<%= f.text_field :city, :placeholder => "City",
				id: "city", class: "box2", onChange: "codeAddress()" %>
		<br><br>
	</span>
    <span>
    	<%= f.label "Location: ", :for => :address, :class => "pad10" %>
		<%= f.text_field :address, :placeholder => "Street Address",
				id: "location", class: "box1", onChange: "codeAddress()" %>
        <br><br>
    </span>
    <span style = "padding-bottom:4px">
    	<%= f.label "Time: ", :for => :start_date, :class => "pad10" %>
    	<%= f.datetime_select :start_date %>
        <br><br>
    </span>
    <span>
        <%= f.label "Capacity: ", :for => :capacity, :class => "pad10" %><%= f.number_field :capacity, :placeholder => "Capacity", :min => 1 %>
		<br><br>
    </span>
    <span style="clear:both">
    	<p>
    		<span class="middle-align-inline">Preview image:</span>
    		<%= image_tag @party.avatar.url(:thumbnail), :width => 100, :height => 100, :class => "middle-align-inline", :style => "margin-left: 1em;" %>
    	</p>
    	<br>
    	<%= f.label "Change image", :for => :avatar, :class => "pad10" %>
    	<span style="padding-left:20px">
    		<%= f.file_field :avatar %>
    	</span>
    	<br><br>
    </span>
    <span style="clear:both">
    	<%= f.label "Description: ", :for => :description, :class => "pad10" %>
        <span style="padding-left:20px">
        	<%= f.text_area :description, :rows => 8, :class => "box1 ta" %>
        </span>
        <br><br>
    </span>
    <div style="clear:both">
        <br>
        <span>
        	<%= f.check_box :food_provided %><%= f.label "Food/Drinks Provided", :for => :food_provided %>
        </span>
        <span>
        	<%= f.check_box :alcohol %><%= f.label "Alcohol", :for => :alcohol %>
        </span>
        <span>
        	<%= f.check_box :parking %><%= f.label "Parking", :for => :parking %>
        </span>
        <span>
        	<%= f.check_box :adult_only %><%= f.label "18+", :for => :adult_only %>
        </span>
        <span>
        	<%= f.check_box :streaming %><%= f.label "Live Stream?", :for => :streaming %>
        </span>
    </div>
    <br>
	<!--<label class="pad10">Upload Pictures: </label><br>
	<input type="file" name="uploaded" id="uploaded" onChange="getName();" multiple></input>
	<input type="hidden" name = "uploaded_values" id = "uploaded_values"></input>
	<script>
		function getName() {
			var file_names = document.getElementById("uploaded").files;
			var one_line = "";
			for (var i = 0; i < file_names.length; i++){
				if (i != file_names.length - 1) {
					one_line += (file_names[i].name + ",");
				} else {
					one_line += file_names[i].name;
				}
			}
			document.getElementById("uploaded_values").value = one_line;
		} -->
	<%= f.submit "Submit", :class => "button" %>
<% end %>

A3/HousePartyFinder/app/views/parties/show.html.erb
<% content_for :head do %>
  <link rel="stylesheet" type="text/css" href="/styles/party-info.css" >
      <!-- Raty -->
    <link href="/raty/jquery.raty.css" rel="stylesheet">
    <script src="/raty/jquery.raty.js"></script>
    <script>
      function raty_update() {
        $('.rating').html("").raty({
          score: function() {
            return $(this).attr('data-score');
          },
          readOnly: function() {
            return $(this).hasClass('read-only');
          },
          click: function(score) {
            if ($(this).hasClass('rating-submitter')) {
              var form = $("form#" + $(this).attr("form-id"));
              form.find("input[name=rating\\[score\\]]").val(score);
              form.trigger('submit.rails');
              $("#rating-form").on('ajax:success', function(event, data, status, xhr) {
                if (data.ok) {
                  $('.rating-submitter').raty('set', {
                    score: data.score
                  });
                  $('.rating-count-text').html(data.count + ((data.count == 1) ? " Rating" : " Ratings"));
                }
              });
            }
          }
        });
      }
      $(function() {
        raty_update();
      });
    </script>
    <script>
        function initialize() {
      var marker;
          var map_canvas = document.getElementById('map_canvas');
      var pos = new google.maps.LatLng(<%== @party.latitude %>, <%== @party.longitude %>);
          var map_options = {
            center: pos,
            zoom: 14,
            mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          var map = new google.maps.Map(map_canvas, map_options)
      marker = new google.maps.Marker({
        position: pos,
        map:map,
        title: "Party Address"
      });
      //marker.setPosition(results[0].geometry.location);
      }
        google.maps.event.addDomListener(window, 'load', initialize);
      </script>
      
    <!-- jQuery -->
    <script>
      $(document).ready(function(){
        // $("#party-completed").on("click", function(e) {
        //   $.ajax({
        //     url:'/parties/completed',
        //     type: "POST",
        //     data: {page: window.location.pathname.replace("/parties/", "")}
        //   });
        //   e.preventDefault();
        $("#complete-form").on('ajax:success', function(event, data, status, xhr) {
          if (data.ok && data.ended) {
            $(".completed").css("background-color", "red");
            $('.completed').html("This party has been completed!");
            $("#party-completed").attr('disabled', true);
            $('#party-completed').attr("value", "Finished!");
            $('#party-completed').removeClass('button').addClass('button-disabled');
          }
        });
        // });
      });
    </script>
    <!-- Fotorama -->
    <link href="../fotorama-4.5.1/fotorama.css" rel="stylesheet">
    <script src="../fotorama-4.5.1/fotorama.js"></script>
<% end %>

<% content_for :title, @party.name %>

<section class="party-info" >
    <div class="name-host-pic-status">
      <div class="name-host-pic">
        <%= image_tag @party.avatar.url(:thumbnail), :width => 100, :height => 100 %>
        <h1 name="pname"><%= @party.name %></h1>
        <h2>Hosted by <%= @party.host.username %></h2>
        <h2 name="date">Date: <%= @party.start_date.strftime("%F %r") %></h2>
        <div style="float: right; margin-right: 0.5em; margin-bottom: 0.5em;">
          <% if signed_in? && @party.host != current_user %>
	    <% if current_user.admin != true %>
	      <% if @party.attendees.include?(current_user) %>
		<%= link_to "Opt-out of this party", party_unattend_path(@party), :class => 'button', :method => :post %>
	      <% elsif @party.attendees.count < @party.capacity %>
		<%= link_to "Attend this party", party_attend_path(@party), :class => 'button', :method => :post %>
	      <% end %>
            <% else %>
            
	      <%if @party.featured_until == nil%>
		<%= link_to "Feature this party", party_feature_path(@party), :class => 'button', :method => :post %>
	      <% end %>
	      <% if @party.featured_until != nil %>
		<% if @party.featured_until <= Date.today %> 
		  <%= link_to "Feature this party", party_feature_path(@party), :class => 'button', :method => :post %>
		
		<% else %>
		  <%= link_to "Unfeature this party", party_unfeature_path(@party), :class => 'button', :method => :post %>
		<% end %>
	      <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if @party.ended %>
        <h3 class="completed" style="background-color: red">This party has been completed!</h3>
        <button id="party-completed" class="button-disabled" type="submit" disabled>Finished!</button>
    <% else %>
        <h3 class="completed">This party has not been completed!</h3>
        <% if signed_in? && @party.host == current_user %>
	  <%= form_for @party, url: "/parties/#{@party.id}/complete", html: { id: "complete-form" }, remote: true do |f| %>
	      <%= f.submit "Complete", id: "party-completed", class: "button" %>
	  <% end %>
        <% end %>
    <% end %>
    </div>
    <% unless @party.album_attachments.empty? && current_user != @party.host %>
    <div class="album">
        <h2>Party Album</h2>
        <!-- Fotorama -->
        <div class="fotorama">
            <% @party.album_attachments.each do |album_attachment| %>
              <%= image_tag album_attachment.picture.url %>
            <% end %>
        </div>
        <br>
	  <% if signed_in? && @party.host == current_user %>
	    <%= form_for :album_attachment, url: party_attach_path(@party), html: { multipart: true } do |f| %>
	      <%= f.label "Upload a picture:", :for => :picture %><br>
	      <%= f.file_field :picture %>
	      <%= f.submit "Upload", :class => "button" %>
	    <% end %>
	  <% end %>
    </div>
    <% end %>
    <div class="party-description">
      <h2>Party Description</h2>
      <div class="clear"></div>
      <div class="party-description-text">
        <p name="party-description"><%= @party.description %></p>
        <p name="location">Address: <%= @party.address + ", " + @party.city + ", " + @party.province %></p> 
        <p name="capacity">Capacity: <%= @party.attendees.count %>/<%= @party.capacity %> <br />
        <p>Food Provided: <%= @party.food_provided ? "YES" : "NO" %></p>
        <p>Alcohol Provided: <%= @party.alcohol ? "YES" : "NO" %></p>
        <p>Parking Provided: <%= @party.parking ? "YES" : "NO" %></p>
        <p>Adults Only: <%= @party.adult_only ? "YES" : "NO" %></p>
        </p>
      </div>
      <div id="map_canvas"></div>
    </div>

    <% if @party.streaming && !@party.ended %>
      <div class="live-stream">
        <h2>Live Streaming</h2>
        <% if current_user == @party.host %>
          <iframe src="/parties/<%= @party.id %>/stream_in" style="width:320px; height:300px; overflow: hidden;"></iframe>
        <% else %>
          <iframe src="/parties/<%= @party.id %>/stream_out" style="width:320px; height:300px; overflow: hidden;"></iframe>
        <% end %>
      </div>
    <% end %>          
  </section>
  <section class="side-bar" >
    <div class="party-rating">
      <div class = "rating<%= @allowed_to_rate ? ' rating-submitter' : ' read-only' %>" data-score="<%= @party.rating_score %>" form-id="rating-form"></div>
      <p>(<span class="rating-count-text"><%= pluralize(@party.rating_count, "Rating") %></span>)</p>
        <% if @allowed_to_rate %>
          <%= form_for :rating, url: "/parties/#{@party.id}/rate", html: { id: "rating-form" }, remote: true do |f| %>
            <%= f.hidden_field :score %>
          <% end %>
        <% end %>
    </div>
    <div class="similar-parties">
      <h2>Similar Parties</h2>

      <% if @similar_parties.empty? %>
        <div class="div-similar-party">
          <h3>No similar parties.</h3>
        </div>
      <% else %>
        <% @similar_parties.each do |party| %>
          <%= link_to party_url(party) do %>
            <div class="div-similar-party">
              <%= image_tag party.avatar.url(:thumbnail), :width => 64, :height => 64 %>
              <div class="div-similar-party-description">
                <p><%= party.name %></p>
                <p class="party-date"><%= party.start_date.strftime("%F") %></p>
                <span class="rating read-only" data-score="<%= party.rating_score %>"><%= party.rating_score %></span>
                <p style="display: inline;">(<%= party.rating_count %>)</p>
                <div class="clear"></div>
                <p>
                  <%= truncate party.description, length: 30 %>           
                </p>    
              </div>        
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  
  </section>