A3/HousePartyFinder/config/routes.rb
Rails.application.routes.draw do

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#rejected'
  get '/500', :to => 'errors#server_error'

  root 'static_pages#home'
  get 'register_login' => 'static_pages#register_login'
  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'site_map' => 'static_pages#site_map'
  get 'about_us' => 'static_pages#about_us'

 devise_for :users do
    resource :registration, :only => [:new, :create, :edit, :update],
      as: :user_registration do
        get :cancel
      end
  end
  
  get '/parties/featured' => 'parties#featured'
  get '/parties/streaming' => 'parties#streaming'
  get '/parties/my-parties' => 'parties#mine'
  resources :parties do
    post 'attend' => 'parties#attend', :as => :attend
    post 'unattend' => 'parties#unattend', :as => :unattend
    post 'feature' => 'parties#feature', :as => :feature
    post 'unfeature' => 'parties#unfeature', :as => :unfeature
    post 'attach' => 'parties#attach', :as => :attach
    get 'stream_in' => 'parties#stream_in', :as => :stream_in
    get 'stream_out' => 'parties#stream_out', :as => :stream_out
  end
  post '/parties/:id/rate' => 'parties#rate'
  patch '/parties/:id/complete' => 'parties#complete'
  
  resources :users do
    get 'profile' => 'users#profile', :as => :profile
    get 'activity' => 'users#activity', :as => :activity
    get 'subscribers' => 'users#subscribers', :as => :subscribers
    get 'portfolio' => 'users#portfolio', :as => :portfolio
    post 'subscribe' => 'users#subscribe', :as => :subscribe
    post 'unsubscribe' => 'users#unsubscribe', :as => :unsubscribe
  end
  

end

A3/HousePartyFinder/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :ratings
  has_many :rated_parties, :through => :ratings, :source => :party
  has_many :subscriptions
  has_many :subscribers, :through => :subscriptions, :source => :subscriber
  has_many :out_subscriptions, :class_name => 'Subscription', :foreign_key => 'subscriber_id'
  has_many :out_subscribers, :through => :out_subscriptions, :source => :user
  has_many :hosted_parties, :class_name => 'Party', :foreign_key => 'host_id'
  has_many :album_attachments, :through => :hosted_parties
  has_many :received_ratings, :through => :hosted_parties, :source => :ratings
  has_many :attendances
  has_many :attended_parties, :through => :attendances, :source => :party

  has_attached_file :avatar, :url => '/system/uploads/avatar_:style_:id.:extension', :path => ":rails_root/public:url", :styles => { :medium => "240x240>", :thumbnail => "64x64>" }, :default_url => "/images/default-avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :username, :uniqueness => true, :presence => true
  validates :first_name, :last_name, :address, :city, :province, :presence => true
  validates :latitude, :longitude, :numericality => true

  def rating_score
  	User.where({ id: self.id }).joins(:received_ratings).average(:score)
  end

  def rating_count
  	User.where({ id: self.id }).joins(:received_ratings).count
  end

  def join_date
    self.created_at
  end
end

A3/HousePartyFinder/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_fragment_user, only: [:profile, :activity, :subscribers, :portfolio, :subscribe, :unsubscribe]
  layout "user_fragment", only: [:profile, :activity, :subscribers, :portfolio]
  before_action :owner_only, only: [:edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  # GET /users/1/profile
  def profile
  end

  # GET /users/1/activity
  def activity
    @attended_parties = @user.attended_parties.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /users/1/subscribers
  def subscribers
    @subscribers = @user.subscribers.paginate(:page => params[:page], :per_page => 24)
  end

  # GET /users/1/portfolio
  def portfolio
    @hosted_parties = @user.hosted_parties.paginate(:page => params[:page], :per_page => 12)
  end

  # POST /users/1/subscribe
  def subscribe
    unless @user.subscribers.include?(current_user) || @user == current_user
      @user.subscribers << current_user
      @user.save
    end
    redirect_to :back
  end

  # POST /users/1/unsubscribe
  def unsubscribe
    if @user.subscribers.include?(current_user)
      @user.subscribers.delete(current_user)
      @user.save
    end
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def set_fragment_user
      @user = User.find(params[:user_id])
    end

    # Restrict to owner only
    def owner_only
      unless @user == current_user
        redirect_to root_url, notice: "You must be logged in as that user to make this change."
      end
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :email, :join_date, :address, :city, :province, :latitude, :longitude, :avatar)
    end
end

A3/HousePartyFinder/app/helpers/users_helper.rb
module UsersHelper
end

A3/HousePartyFinder/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :join_date %><br>
    <%= f.date_select :join_date %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

A3/HousePartyFinder/app/views/users/activity.html.erb
<% content_for :head do %>
	<style>
		.activity-entry {
			display: block;
			margin: 0.4em;
			padding: 0.4em;
			border-radius: 0.4em;
			background-color: white;
			overflow-y: auto;
		}

		.activity-entry > img {
			float: left;
			display: block;
		}

		.activity-entry .entry-description {
			display: block;
			margin-left: 112px;
			width: auto;
		}

		.activity-entry .title-block {
			float: left;
		}

		.activity-entry .rating-block {
			float: right;
			margin: 0.2em 0;
		}

		.activity-entry p {
			margin-top: 0.6em;
		}

		.clear {
			clear: right;
		}
	</style>
<% end %>

<% if @attended_parties.count == 0 %>
	<p class="no-result">This user has yet to attend a party.<p>
<% else %>
	<ul>
		<% @attended_parties.each do |party| %>
			<li class="activity-entry">
				<%= image_tag party.avatar.url(:thumbnail), :width => 100, :height => 100 %>
				<div class="entry-description">
					<div class="title-block">
						Attended: <a href="/parties/<%= party.id %>" target="_parent"><%= party.name %></a> (<%= party.start_date.strftime("%F %r") %>)
					</div>
					<div class="rating-block">
						<span class="rating read-only" data-score="<%= party.rating_score %>"><%= party.rating_score %></span>
						<span>(<%= party.rating_count %>)</span>
					</div>
					<div class="clear"></div>
					<p>
						Location: <%= party.address %>, <%= party.city %>, <%= party.province %><br>
						Description: <%= party.description %>
					</p>
					<p><a href="/parties/<%= party.id %>" target="_parent">View details</a></p>		
				</div>				
			</li>
		<% end %>
	</ul>
	<p><%= will_paginate @attended_parties %></p>
<% end %>

A3/HousePartyFinder/app/views/users/edit.html.erb
<% content_for :head do %>
	<link rel="stylesheet" href="/styles/homepage.css">
	<script>
		$(function() {

		});
	</script>
	<style>
		#form-block {
			display: block;
			float: left;
			width: 50%;
			margin-right: 1em;
			margin-top: 1em;
		}

		#form-block input[type=text] {
			width: 100%;
		}

		#map-canvas {
			width: 300px;
			height: 300px;
			float: right;
			margin-right: 2em;
			margin-top: 1em;
		}

		@media (max-width:1000px) {
			#form-block {
				width: 95%;
			}

			#map-canvas {
				margin-right: 0;
				float: left;
			}
		}

		.field {
			margin-bottom: 0.7em;
		}

		.middle-align-inline {
			display: inline-block;
			vertical-align: middle;
		}
	</style>
<% end %>

<% content_for :title, "Account Settings" %>

<div class="featured-heading">
	<h2>Updating Your Profile</h2>
</div>

<div id="form-block">

	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= form_for(@user, :html => { :multipart => true }) do |f| %>
		<div class="field">
			<%= f.label :first_name %><br>
			<%= f.text_field :first_name %>
		</div>
		<div class="field">
			<%= f.label :last_name %><br>
			<%= f.text_field :last_name %>
		</div>
		<div class="field">
			<%= f.label :email %><br>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :province %><br>
			<%= f.select :province, [
						["-- Select province --", "none"],
						["Alberta", "AB"],
						["British Columbia", "BC"],
						["Manitoba", "MB"],
						["New Brunswick", "NB"],
						["Newfoundland and Labrador", "NL"],
						["Nova Scotia", "NS"],
						["Ontario", "ON"],
						["Prince Edward Island", "PE"],
						["Quebec", "QC"],
						["Saskatchewan", "SK"],
						["Northwest Territories", "NT"],
						["Nunavut", "NU"],
						["Yukon", "YT"]
					], {}, id: "province", onChange: "clearCity(); codeAddress()" %>
		</div>
		<div class="field">
			<%= f.label :city %><br>
			<%= f.text_field :city,
				id: "city", onChange: "codeAddress()" %>
		</div>
		<div class="field">
			<%= f.label :address %><br>
			<%= f.text_field :address,
				id: "location", onChange: "codeAddress()" %>
		</div>

		<%= f.hidden_field :latitude, id: "latitude" %>
		<%= f.hidden_field :longitude, id: "longitude" %>

		<div class="field">
			<span class="middle-align-inline">Current avatar: <%= image_tag @user.avatar.url(:thumbnail), :width => 64, :height => 64, :class => "middle-align-inline" %>
		</div>
		
		<div class="field">
			<%= f.label "Choose new avatar:", :for => :avatar %>
			<%= f.file_field :avatar %>
		</div>

		<div class="actions">
			<%= f.submit "Update", :class => "button" %>
		</div>
	<% end %>
</div>

<div id="map-canvas"></div>

<div class="clear"></div>

<div class="featured-heading">
	<h2>Change Password</h2>
</div>

<div class="form-block">
	<%= form_for(@user, url: user_registration_path, html: { method: :put }) do |f| %>

		<div class="field">
		  	<%= f.label :password %> (Leave blank for unchanged)<br>
		    <%= f.password_field :password, autocomplete: "off" %>
		</div>

		<div class="field">
			<%= f.label :password_confirmation %><br>
		    <%= f.password_field :password_confirmation, autocomplete: "off" %>
		</div>

		<div class="field">
			<%= f.label :current_password %> (Must be filled to change password)<br>
		    <%= f.password_field :current_password, autocomplete: "off" %>
		</div>

		<div class="actions">
			<%= f.submit "Update Password", :class => "button" %>
		</div>
	
	<% end %>
</div>

A3/HousePartyFinder/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Join date</th>
      <th>Address</th>
      <th>City</th>
      <th>Province</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.join_date %></td>
        <td><%= user.address %></td>
        <td><%= user.city %></td>
        <td><%= user.province %></td>
        <td><%= user.latitude %></td>
        <td><%= user.longitude %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

A3/HousePartyFinder/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

A3/HousePartyFinder/app/views/users/portfolio.html.erb
<% content_for :head do %>
	<style>
		.activity-entry {
			display: block;
			margin: 0.4em;
			padding: 0.4em;
			border-radius: 0.4em;
			background-color: white;
			overflow-y: auto;
		}

		.activity-entry > img {
			float: left;
			display: block;
		}

		.activity-entry .entry-description {
			display: block;
			margin-left: 112px;
			width: auto;
		}

		.activity-entry .title-block {
			float: left;
		}

		.activity-entry .rating-block {
			float: right;
			margin: 0.2em 0;
		}

		.activity-entry p {
			margin-top: 0.6em;
		}

		.clear {
			clear: right;
		}
	</style>
<% end %>

<% if @hosted_parties.count == 0 %>
	<p class="no-result">This user has yet to host a party.<p>
<% else %>
	<ul>
		<% @hosted_parties.each do |party| %>
			<li class="activity-entry">
				<%= image_tag party.avatar.url(:thumbnail), :width => 100, :height => 100 %>
				<div class="entry-description">
					<div class="title-block">
						<a href="/parties/<%= party.id %>" target="_parent"><%= party.name %></a> (<%= party.start_date.strftime("%F %r") %>)
					</div>
					<div class="rating-block">
						<span class="rating read-only" data-score="<%= party.rating_score %>"><%= party.rating_score %></span>
						<span>(<%= party.rating_count %>)</span>
					</div>
					<div class="clear"></div>
					<p>
						Location: <%= party.address %>, <%= party.city %>, <%= party.province %><br>
						Description: <%= party.description %>
					</p>
					<p><a href="/parties/<%= party.id %>" target="_parent">View details</a></p>		
				</div>				
			</li>
		<% end %>
	</ul>
	<p><%= will_paginate @hosted_parties %></p>
<% end %>

A3/HousePartyFinder/app/views/users/profile.html.erb
<% content_for :head do %>
	<style>
		#profile-frag-container {
			display: block;
			float: left;
		}

		#profile-frag-container h1 {
			font-size: 1.6em;
			font-weight: bold;
			margin-bottom: 0.6em;
		}

		#profile-frag-container ul {
			margin-top: 1em;
		}

		#profile-frag-container ul li {
			margin-top: 0.2em;
		}

		#map_canvas {
			float: right;
			width: 280px;
			height: 280px;
		}

		@media (max-width: 800px) {
			#map_canvas {
				float: left;
			}
		}
	</style>

	<script src="https://maps.googleapis.com/maps/api/js"></script>
	<script>
		google.maps.event.addDomListener(window, 'load', function() {
			var pos = new google.maps.LatLng(<%= @user.latitude %>, <%= @user.longitude %>);
			var map_canvas = document.getElementById('map_canvas');
			var map_options = {
				center: pos,
				zoom: 16,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			var map = new google.maps.Map(map_canvas, map_options);
			var marker = new google.maps.Marker({
				position: pos,
				map: map,
				title: 'Party Address'
			});
		});
	</script>
<% end %>

<div id="profile-frag-container">
	<h1>Profile</h1>
	<ul>
		<li>Real name: <%= @user.first_name %> <%= @user.last_name %></li>
		<li>Joined: <%= @user.created_at.strftime("%F") %></li>
	</ul>
	<ul>
		<li>Parties created: <%= @user.hosted_parties.count %></li>
		<li>Parties attended: <%= @user.attended_parties.count %></li>
	</ul>
	<ul>
		<li>
			Home address:
			<p>
				<%= @user.address %>,<br>
				<%= @user.city %>, <%= @user.province %>
			</p>
		</li>
	</ul>
</div>

<div id="map_canvas"></div>

A3/HousePartyFinder/app/views/users/show.html.erb
<% content_for :head do %>
  <!-- Fotorama -->
  <link href="/fotorama-4.5.1/fotorama.css" rel="stylesheet">
  <script src="/fotorama-4.5.1/fotorama.js"></script>
  <!-- Raty -->
  <link href="/raty/jquery.raty.css" rel="stylesheet">
  <script src="/raty/jquery.raty.js"></script>
  <script>
    function raty_update() {
      $('.rating').html("").raty({
        score: function() {
          return $(this).attr('data-score');
        },
        readOnly: function() {
          return $(this).hasClass('read-only');
        }
      });
    }
    $(function() {
      raty_update();
    });
  </script>
  <!-- Page style -->
  <style>
    #user-page .user-name, #user-page .user-rating {
      margin-top: 1.4em;
    }

    #user-page .user-name {
      float: left;
    }

    #user-page .user-name > img, #user-page .user-name > h1 {
      display: inline-block;
      vertical-align: middle;
    }

    #user-page .user-rating {
      float: right;
    }

    #user-page .user-rating > img, #user-page .user-rating > p {
      display: inline-block;
      vertical-align: middle;
    }

    .user-nav {
      display: block;
      margin-top: 1.4em;
    }

    .user-nav > li {
      display: inline-block;
    }

    .user-nav > li a {
      display: block;
      background-color: navy;
      color: white;
      text-decoration: none;
      padding: 0.4em;
      border: 2px navy solid;
    }

    #dynamic-box {
      display: block;
      width: 100%;
      border: 2px navy solid;
      height: 480px;
    }
  </style>
<% end %>

<% content_for :title, "User: #{@user.username}" %>

<div id="user-page">
  <div class="fotorama" data-width="100%" data-height="128" data-loop="true" data-autoplay="true" data-nav="thumbs" data-navposition="top">
    <% @user.album_attachments.each do |album_attachment| %>
      <%= image_tag album_attachment.picture.url %>
    <% end %>
  </div>
  <div class="user-name">
    <%= image_tag @user.avatar.url(:thumbnail), :width => 64, :height => 64 %>
    <h1><%= @user.username %></h1>
  </div>
  <div class="user-rating">
    <div class="rating read-only" data-score="<%= @user.rating_score %>"><%= @user.rating_score %></div> 
    <p>(<%= pluralize(@user.rating_count, "Ratings") %>)</p>
    <% if signed_in? && current_user != @user %>
      <br><br><p>
        <% if @user.subscribers.include?(current_user) %>
          <%= link_to "Unsubscribe", user_unsubscribe_path(@user), :method => :post, :class => "button" %>
        <% else %>
          <%= link_to "Subscribe", user_subscribe_path(@user), :method => :post, :class => "button" %>
        <% end %>
      </p>
    <% end %>
  </div>
  <div class="clear"></div>
  <ul class="user-nav">
    <li><a href="/users/<%= @user.id %>/profile" class="dynamic-load" target="dynamic-box">Profile</a></li>
    <li><a href="/users/<%= @user.id %>/activity" class="dynamic-load" target="dynamic-box">Activity</a></li>
    <li><a href="/users/<%= @user.id %>/subscribers" class="dynamic-load" target="dynamic-box">Subscribers</a></li>
    <li><a href="/users/<%= @user.id %>/portfolio" class="dynamic-load" target="dynamic-box">Portfolio</a></li>
  </ul>
  <iframe name="dynamic-box" src="/users/<%= @user.id %>/<%= params[:frag] || 'profile' %>" id="dynamic-box"></iframe>
</div>

A3/HousePartyFinder/app/views/users/subscribers.html.erb
<% content_for :head do %>
	<style>
		.subscriber-entry {
			display: inline-block;
			margin: 0.6em;
			padding: 0.6em;
			border-radius: 0.6em;
			background-color: white;
			width: 27.5%;
		}

		.subscriber-entry > img {
			float: left;
			display: block;
		}

		.subscriber-entry .entry-description {
			display: block;
			margin-left: 112px;
			width: auto;
		}

		.subscriber-entry p {
			margin-top: 0.6em;
		}

		/* ignore below, erase */
		.clear {
			display: block;
			clear: right;
		}
	</style>
<% end %>

<% if @subscribers.count == 0 %>
	<p>This user has no subscribers.</p>
<% else %>
	<ul>
		<% @subscribers.each do |subscriber| %>
			<li class="subscriber-entry">
				<img src="/images/homepage-images/1_copy(1).JPG">
				<div class="entry-description">
					<div class="title-block">
						<a href="/users/<%= subscriber.id %>"><%= subscriber.username %></a>
					</div>
					<div class="rating-block">
						<span class="rating read-only" data-score="<%= subscriber.rating_score %>"><%= subscriber.rating_score %></span>
						<span>(<%= subscriber.rating_count %>)</span>
					</div>
					<div class="clear"></div>
					<p>
						Joined: <%= subscriber.join_date.strftime("%F") %>
					</p>
					<p><a href="/users/<%= subscriber.id %>">View details</a></p>		
				</div>				
			</li>
		<% end %>
	</ul>
	<p><%= will_paginate @subscribers %></p>
<% end %>